kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: amd64

steps:
  - name: build migration image
    commands:
      - make build-migration

  - name: build application
    commands:
      - make build

  - name: push migration image
    commands:
      - make push-migration

  - name: push application
    commands:
      - make push

trigger:
  branch:
    - main