apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetdb
spec:
  selector:
    matchLabels:
      app: budgetdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: budgetdb
    spec:
      containers:
        - name: budgetdb
          image: postgres
          env:
            - name: POSTGRES_DB
              value: budget
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: budgetdb
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: budgetdb-storage
      volumes:
        - name: budgetdb-storage
          persistentVolumeClaim:
            claimName: postgres-claim
