apiVersion: batch/v1
kind: Job
metadata:
  name: budgetdb-migration-job
spec:
  template:
    spec:
      containers:
        - name: budgetdb-migration-job
          image: registry.digitalocean.com/budgetapp-registry/budget-migration:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_SERVER
              value: budgetdb
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: budget
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: budgetdb
                  key: password
          command: ["dotnet", "ef", "database", "update"]
      restartPolicy: OnFailure
  backoffLimit: 4
