apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgetapi
  template:
    metadata:
      labels:
        app: budgetapi
    spec:
      containers:
        - name: budgetapi
          image: docker-registry.home.arpa/mybudget/budgetapi:latest
          imagePullPolicy: Always
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: token
                  name: jwt
            - name: POSTGRES_SERVER
              value: postgresql.db
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USER
              value: budget
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: budget
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: budgetdb
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-password
                  name: rabbitmq
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: redis
            - name: UpdateConsumer__UserName
              value: authservice
            - name: UpdateConsumer__HostName
              value: rabbitmq.db
            - name: UpdateConsumer__VirtualHost
              value: mybudget-staging
            - name: UpdateConsumer_Port
              value: '5672'
            - name: RedisSettings__Hostname
              value: redis-master.db:6379
    
