apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgetapi
  template:
    metadata:
      labels:
        app: budgetapi
    spec:
      containers:
        - name: budgetapi
          image: registry.digitalocean.com/budgetapp-registry/budgetapi:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: token
            - name: POSTGRES_SERVER
              value: budgetdb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: budgetdb
                  key: password
            - name: RABBITMQ_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: rabbitmq
                 key: rabbitmq-password
    
