name: Build and push docker images
on:
  push:
    branches:
      - deploy
    paths:
      - 'BudgetModel/**'
      - 'BudgetServices/**'
      - 'BudgetWebApi/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch deploy
        uses: actions/checkout@v2
        with:
          ref: deploy
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Build database migration image
        run: docker build --platform linux/amd64 -f migration.dockerfile -t ${{ secrets.DO_REGISTRY_NAME }}/budget-migration:latest .
      - name: Build budgetapi image
        run: docker build --platform linux/amd64 -f budgetapi.dockerfile -t ${{ secrets.DO_REGISTRY_NAME }}/budgetapi:latest .
      - name: Login to Digital Ocean
        run: doctl registry login --expiry-seconds 1200
      - name: Push database migration image
        run: docker push ${{ secrets.DO_REGISTRY_NAME }}/budget-migration:latest
      - name: Push budgetapi image
        run: docker push ${{ secrets.DO_REGISTRY_NAME }}/budgetapi:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch deploy
        uses: actions/checkout@v2
        with:
          ref:
            deploy
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Set context
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 do-ams3-cluster-budgetapp
      - name: Configure deployment
        run: kubectl apply -f $GITHUB_WORKSPACE/BudgetWebApi/budgetapi-deployment.yaml
      - name: Configure service
        run: kubectl apply -f $GITHUB_WORKSPACE/BudgetWebApi/budgetapi-service.yaml
      - name: Restart deployment
        run: kubectl rollout restart deployment/budgetapi